### ISSUE TITLE
Add a option to search for user and email in ~/.gitconfig

### ISSUE THREAD

**Issue by FxmousKid** [Diogo-ss/42-header.nvim#10]
First of all thanks a lot for writing this very useful extension for us nvim users.

My suggestion is basically this : have a option that will make the header email and user be based on the info of the gitconfig, if it's a repo the file being edited is currently in.

I'm pretty sure this is not as straightforward as i make it sound, and would love to help you with this if you need any help.

**Comment by Diogo-ss** [comment]
Thank you very much for your feedback. 
You've really come up with a great idea. I don't think it will be that difficult to develop this feature. 

I've created a branch to develop it, pull requests are welcome :D
As soon as I have some free time, I'll start working on it.

**Comment by FxmousKid** [comment]
No problem man ! this kind of personal work is very much appreciated, when
i see that someone devoted time for something that will help others and
still maintain it, it really makes me respect them.

As for a potential pull request, i'll have a look at the dev branch and
potentially do one when i have time and get familiar with your source code.
Would you mind if i asked you some implementation questions? (i'm still new
to neovim, and have basically no experience in lua, sorry, but i'll learn
!).

Thank you and have a great day

**Comment by Diogo-ss** [comment]
If you have any questions, feel free to ask. I'll try to help.
