### ISSUE TITLE
Instalação no Astrovim

### ISSUE THREAD

**Issue by FigueiredoStable** [Diogo-ss/42-header.nvim#2]
Hey Diogo, tentei instalar através do instalador lazy.nvim sem sucesso, uso com o Astrovim no MacOS. Pode me ajudar?

**Comment by Diogo-ss** [comment]
Tem alguma mensagem de erro?

- Testando no AstroVim, criei um arquivo "header.lua" na pasta de user/plugins e foi instalado com sucesso.
![image](https://user-images.githubusercontent.com/86174715/236185799-e383ee64-417d-4ed2-8520-1b415f15bff1.png)

```lua
return {
    "Diogo-ss/42-header.nvim",
    lazy = false,
    config = function()
        local header = require("42header")
        header.setup({
            default_map = true, -- Default Mapping <F1> in normal mode
            auto_update = true,  -- Update header when saving
            user = "Diogo-ss", -- Your user
            mail = "contact@diogosilva.dev", -- Your mail
        })
    end
}
```

**Comment by Diogo-ss** [comment]
Realmente, vou adicionar no readme.
Que bom que deu certo. Tmj.
