### ISSUE TITLE
Bad commentstring

### ISSUE THREAD

**Issue by Magikh42** [Diogo-ss/42-header.nvim#22]
Hello, 

Since a few days `:Stdheader` uses "`//`" for comments instead of "`/*`"
From what I found in the code of this plugin it seems to use "`vim.api.nvim_buf_get_option(0, "commentstring")`" but I don't know why neovim suddendly changed the comment string for `.h` and `.c` files

**Comment by Magikh42** [comment]
I'll tell you the next time I go to the school
I think it is the default Neovim version on clusters' computers (at least in 42 Lyon) because other students have the the same problem

Also I solved it using a autocmd:

```
local function augroup(name)
	return vim.api.nvim_create_augroup("lazyvim_config_" .. name, { clear = true })
end

vim.api.nvim_create_autocmd("FileType", {
	group = augroup("commentstring"),
	pattern = { "c", "cpp" },
	callback = function()
		vim.opt.commentstring = "/* %s */"
	end,
	desc = "Change commentstring for c/c++ files",
})
```

It seems the default commantstring for `c` and `cpp` changed in newer versions of Neovim
I think `42-header.nvim` plugin should override it to `"/* %s */"` for `c` (and maybe `cpp`) files because there is no reason to use the commentstring setting when [the norm states that it must be block comment](https://github.com/42School/norminette/blob/master/norminette/rules/check_header.py) `"/* %s */"` and not lines comment `"// %s //"`

**Comment by Diogo-ss** [comment]
A good solution. I will leave the issue open so that others can use this solution until a definitive one is made.
Thank you very much.

**Comment by Magikh42** [comment]
```
➜  ~ which nvim
/usr/bin/nvim
➜  ~ nvim -v        
NVIM v0.11.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

On 42 Lyon computers (Dell, but the problem is also present on Macs so I assume it's the same version)

**Comment by Diogo-ss** [comment]
Thanks for the information. I will soon resolve the problem definitively.
